-- Equinox canonical Supabase schema (synced to the live project)
-- Project ref: kguzdgrlhgbaaksjclnx
-- This file documents the current production schema. It is intentionally
-- idempotent for the core tables, but production schema changes should be
-- applied through reviewed migrations rather than blindly re-running this file.
-- Browser clients MUST use publishable/anon keys only.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  global_rank text not null default 'Unranked',
  equipped_aura_id text,
  auras_collected integer not null default 0,
  collective_rarity numeric not null default 0,
  rarest_roll_rarity bigint not null default 0,
  roll_count bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_length check (char_length(username) between 3 and 20),
  constraint profiles_username_format check (username ~ '^[A-Za-z0-9_]+$')
);

create table if not exists public.game_saves (
  user_id uuid primary key references auth.users(id) on delete cascade,
  save_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.aura_collection (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  aura_id text not null,
  aura_name text not null,
  rarity bigint not null,
  tier text not null,
  rolled_at timestamptz not null default now(),
  favorite boolean not null default false,
  auto_skip boolean not null default false,
  auto_equip boolean not null default false,
  equipped boolean not null default false
);

create table if not exists public.roll_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  roll_number bigint not null,
  aura_id text not null,
  aura_name text not null,
  rarity bigint not null,
  luck numeric not null default 1,
  roll_speed numeric not null default 1,
  biome text not null,
  day_night text not null,
  breakthrough boolean not null default false,
  bonus_roll boolean not null default false,
  rolled_at timestamptz not null default now(),
  unique(user_id, roll_number)
);

create table if not exists public.quest_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  quest_id text not null,
  progress bigint not null default 0,
  completed boolean not null default false,
  completed_at timestamptz,
  primary key(user_id, quest_id)
);

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.achievement_unlocks (
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_id text not null,
  unlocked_at timestamptz not null default now(),
  primary key(user_id, achievement_id)
);

create table if not exists public.global_quests (
  quest_id text primary key,
  hour_key timestamptz not null,
  quest_index smallint not null,
  quest_data jsonb not null,
  created_at timestamptz not null default now(),
  unique(hour_key, quest_index)
);

create table if not exists public.shop_stock (
  item_id text primary key,
  item_name text not null,
  rarity text not null,
  stock integer not null default 0,
  max_stock integer not null default 0,
  hour_key timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.shop_purchases (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id text not null,
  quantity integer not null default 1,
  purchased_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  global_rank text not null default 'Unranked',
  equipped_aura_id text,
  equipped_aura_name text,
  equipped_aura_rarity bigint,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_flags (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.chat_messages(id) on delete cascade,
  flagger_id uuid not null references auth.users(id) on delete cascade,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_bans (
  user_id uuid primary key references auth.users(id) on delete cascade,
  banned_until timestamptz not null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_quotas (
  user_id uuid not null references auth.users(id) on delete cascade,
  quota_day date not null,
  total_qp numeric not null default 0,
  multiplier numeric not null default 1,
  consumed boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key(user_id, quota_day)
);

create table if not exists public.online_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  global_rank text not null default 'Unranked',
  equipped_aura_id text,
  equipped_aura_name text,
  equipped_aura_rarity bigint,
  last_seen timestamptz not null default now()
);

-- All browser-visible tables use RLS.
alter table public.profiles enable row level security;
alter table public.game_saves enable row level security;
alter table public.aura_collection enable row level security;
alter table public.roll_history enable row level security;
alter table public.quest_progress enable row level security;
alter table public.user_settings enable row level security;
alter table public.achievement_unlocks enable row level security;
alter table public.global_quests enable row level security;
alter table public.shop_stock enable row level security;
alter table public.shop_purchases enable row level security;
alter table public.chat_messages enable row level security;
alter table public.chat_flags enable row level security;
alter table public.chat_bans enable row level security;
alter table public.daily_quotas enable row level security;
alter table public.online_presence enable row level security;

-- Production policies are maintained in Supabase and are intentionally not
-- recreated here: policy names have accumulated across migrations. See the
-- live pg_policies catalog before modifying access control.
-- Important ownership rules:
--   profiles: auth.uid() = id
--   all other user-owned tables: auth.uid() = user_id
-- Global quest/shop tables are server-owned; clients may read but must not write.
