-- Equinox Phase 4 backend foundation
-- Authentication uses Supabase Auth. Never use user_metadata for authorization.
-- Client-visible tables all have RLS enabled.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  global_rank text not null default 'Unranked',
  equipped_aura_name text,
  equipped_aura_rarity bigint,
  equipped_title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  rolls bigint not null default 0,
  unique_auras bigint not null default 0,
  collective_rarity numeric not null default 0,
  rarest_roll bigint not null default 0,
  last_seen_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  last_seen_at timestamptz not null default now(),
  current_tab text,
  updated_at timestamptz not null default now()
);

create table if not exists public.global_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  message text not null check (char_length(message) between 1 and 150),
  global_rank text not null default 'Unranked',
  equipped_aura_name text,
  equipped_aura_rarity bigint,
  equipped_title text,
  created_at timestamptz not null default now()
);

create index if not exists global_chat_messages_created_idx
  on public.global_chat_messages(created_at desc);

create table if not exists public.global_chat_flags (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.global_chat_messages(id) on delete cascade,
  flagged_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(message_id, flagged_user_id)
);

create table if not exists public.hourly_shop (
  hour_key bigint not null,
  slot smallint not null check (slot between 1 and 6),
  item_type text not null check (item_type in ('Potion','Gear','Item')),
  item_name text not null,
  price bigint not null check (price >= 0),
  stock integer not null check (stock >= 0),
  initial_stock integer not null check (initial_stock >= 0),
  updated_at timestamptz not null default now(),
  primary key(hour_key, slot),
  unique(hour_key, item_name)
);

create table if not exists public.hourly_quests (
  hour_key bigint not null,
  quest_id integer not null,
  quest_type text not null,
  difficulty smallint not null check (difficulty between 1 and 5),
  objective text not null,
  target numeric not null,
  qp integer not null check (qp > 0),
  created_at timestamptz not null default now(),
  primary key(hour_key, quest_id)
);

create table if not exists public.quest_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  hour_key bigint not null,
  quest_id integer not null,
  progress numeric not null default 0,
  completed_at timestamptz,
  primary key(user_id, hour_key, quest_id)
);

create table if not exists public.daily_quota (
  user_id uuid primary key references auth.users(id) on delete cascade,
  quota_multiplier numeric not null default 1 check (quota_multiplier >= 1),
  source_qp integer not null default 0,
  applied_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.roll_leaderboard_snapshots (
  metric text not null check (metric in ('auras','collective','rarest','rolls')),
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  value numeric not null default 0,
  snapshot_hour bigint not null,
  rank integer,
  primary key(metric, user_id, snapshot_hour)
);

alter table public.profiles enable row level security;
alter table public.player_stats enable row level security;
alter table public.presence enable row level security;
alter table public.global_chat_messages enable row level security;
alter table public.global_chat_flags enable row level security;
alter table public.hourly_shop enable row level security;
alter table public.hourly_quests enable row level security;
alter table public.quest_progress enable row level security;
alter table public.daily_quota enable row level security;
alter table public.roll_leaderboard_snapshots enable row level security;

drop policy if exists "profiles own row" on public.profiles;
create policy "profiles own row" on public.profiles
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "player stats own row" on public.player_stats;
create policy "player stats own row" on public.player_stats
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "presence readable" on public.presence;
create policy "presence readable" on public.presence
  for select to authenticated
  using (true);

drop policy if exists "presence own write" on public.presence;
create policy "presence own write" on public.presence
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "chat readable" on public.global_chat_messages;
create policy "chat readable" on public.global_chat_messages
  for select to authenticated
  using (true);

drop policy if exists "chat own insert" on public.global_chat_messages;
create policy "chat own insert" on public.global_chat_messages
  for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "flags readable" on public.global_chat_flags;
create policy "flags readable" on public.global_chat_flags
  for select to authenticated
  using (true);

drop policy if exists "flag own insert" on public.global_chat_flags;
create policy "flag own insert" on public.global_chat_flags
  for insert to authenticated
  with check ((select auth.uid()) = flagged_user_id);

drop policy if exists "shop readable" on public.hourly_shop;
create policy "shop readable" on public.hourly_shop
  for select to authenticated
  using (true);

drop policy if exists "quests readable" on public.hourly_quests;
create policy "quests readable" on public.hourly_quests
  for select to authenticated
  using (true);

drop policy if exists "quest progress own" on public.quest_progress;
create policy "quest progress own" on public.quest_progress
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "daily quota own" on public.daily_quota;
create policy "daily quota own" on public.daily_quota
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "leaderboards readable" on public.roll_leaderboard_snapshots;
create policy "leaderboards readable" on public.roll_leaderboard_snapshots
  for select to authenticated
  using (true);
